[package]
name = "tools"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "bd24"
path = "src/bd24/main.rs"

[dependencies]
