name: Create release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
  publish:
    needs: build
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        run: rustup target add aarch64-apple-darwin
      - name: Build "aarch64-apple-darwin"
        run: cargo build --release --target=aarch64-apple-darwin